name: Erw&auml;hnenswert
subtitle: ... darum schreibe ich hier
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge

paginate: 5

url: https://blog.lgohlke.de

gems:
 - jekyll-paginate
 - jekyll-feed

feed:
  path: rss.xml

# http://jch.penibelst.de/
compress_html:
  clippings: all
  comments: []
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []

host: 0.0.0.0
port: 4000