name: Erw&auml;hnenswert
subtitle: ... darum schreibe ich hier

paginate: 5

url: https://blog.lgohlke.de

feed:
  path: rss.xml

gems:
 - jekyll-feed
 - jekyll-paginate
 - jekyll-seo-tag
 - jekyll-sitemap

highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
markdown: kramdown

sass:
   sass_dir: _sass
   style: compressed

sitemap: true

host: 0.0.0.0
port: 4000