name: Erw&auml;hnenswert
subtitle: ... darum schreibe ich hier

paginate: 5

url: https://blog.lgohlke.de

# http://jch.penibelst.de/
compress_html:
  clippings: all
  comments: []
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []

feed:
  path: rss.xml

gems:
 - jekyll-paginate
 - jekyll-feed

highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
markdown: kramdown

sass:
   sass_dir: _sass
   style: compressed

host: 0.0.0.0
port: 4000